spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/prueba_metrix
    username: root  
    password: 1717 
    driver-class-name: com.mysql.cj.jdbc.Driver  
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true  
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.MySQLDialect  

  mail:
    host: smtp.gmail.com
    port: 587
    username: marlontorresmedina@gmail.com  
    password: jdte cyxr tzxe mbpp  
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

contact:
  admin-email: recooffee@gmail.com
